Add basic React components to 3ID-UI
ceramicstudio/3id-connect pull request #140
Opened 2021-09-22 17:12 UTC by Sterahi

![Screen Shot 2021-09-22 at 1 11 58 PM](https://user-images.githubusercontent.com/10778536/134390177-ffccc4ca-2f11-41e3-ad6d-c4512aa44a3b.png)
Above is the basic display of the Modal. Still need logo from Sena or we can remove & rebrand slightly.

2021-09-27 13:52 UTC, PaulLeCam commented on apps/3id-ui/src/index.tsx
> +            resolve(true)
Should resolve to `false` no?

2021-09-27 15:31 UTC, Sterahi commented on apps/3id-ui/src/index.tsx
> +            resolve(true)
Totally correct, thanks!

2021-09-27 18:21 UTC, zachferland reviewed
Overall looks good!

I merged some dependency changes in dev that should resolve lint issue here when rebased on develop. Also if you can remove the `apps/3id-ui/.eslintcache` here. Would be good to make sure you can run and build on node16 as well, we should probs align on versions, but CI uses that right now.

Looks like the two high level things that might be missing still are:

1) handlings errors on error notification, this is just really display errors to user 
2) closing the window/exiting, we are also adding better cancellation handling after, but should still be able to use the exiting close/cancel like the iframe does now 

Then we can merge and work more iteratively off the dev branch

2021-09-28 09:15 UTC, PaulLeCam requested changes
Looks like there's both a `package-lock.json` and a `yarn.lock` file, I think that only yarn should be used to be consistent with the rest of the repo.

2021-09-28 19:39 UTC, merged